import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { Boundary } from "../../domain/services/boundary.ts";
import { DesignFlow } from "./design-flow.ts";
import { HarnessLogger } from "../../infrastructure/logging/logger.ts";
import { FLOW_STEP } from "../../domain/model/steps.ts";
import { isReadyLikeStatus } from "../policies/plan-readiness-policy.ts";

function createRegistry(root: string) {
  return {
    getRunner(step: string) {
      return {
        async run(request: { prompt: string }) {
          const match = /## 出力先\n(.+?)\n/.exec(request.prompt);
          if (match) {
            const outputPath = match[1]!;
            mkdirSync(dirname(outputPath), { recursive: true });
            writeFileSync(
              outputPath,
              `---\nstatus: approved\n---\n# generated by ${step}\n`,
              "utf-8",
            );
          }
          return { text: "ok" };
        },
      };
    },
  } as any;
}

test("DesignFlow generates spec and test cases when both are missing", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-"));
  mkdirSync(join(root, "docs", "spec"), { recursive: true });
  mkdirSync(join(root, "tests", "test-cases"), { recursive: true });
  writeFileSync(join(root, "docs", "spec", "TEMPLATE.md"), "# template\n", "utf-8");
  writeFileSync(join(root, "tests", "test-cases", "TEMPLATE.md"), "# template\n", "utf-8");
  const boundary = new Boundary(root);
  const flow = new DesignFlow(boundary, createRegistry(root));
  const logger = new HarnessLogger("design-test", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.match(readFileSync(join(root, "docs", "spec", "quiz", "result.md"), "utf-8"), /approved/);
  assert.match(readFileSync(join(root, "tests", "test-cases", "quiz", "result.md"), "utf-8"), /approved/);
});

test("DesignFlow stops when existing spec is not ready", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-existing-"));
  mkdirSync(join(root, "docs", "spec", "quiz"), { recursive: true });
  writeFileSync(join(root, "docs", "spec", "quiz", "result.md"), "---\nstatus: draft\n---\n", "utf-8");
  const boundary = new Boundary(root);
  const flow = new DesignFlow(boundary, createRegistry(root));
  const logger = new HarnessLogger("design-test-existing", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.equal(isReadyLikeStatus("approved"), true);
  assert.equal(isReadyLikeStatus("draft"), false);
});
