import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { Boundary } from "../../domain/services/boundary.ts";
import { DesignFlow } from "./design-flow.ts";
import { HarnessLogger } from "../../infrastructure/logging/logger.ts";
import { FLOW_STEP } from "../../domain/model/steps.ts";
import { DriftError } from "../../domain/model/types.ts";
import { isReadyLikeStatus } from "../policies/plan-readiness-policy.ts";

function createRegistry(
  root: string,
  options?: {
    generatedStatus?: "approved" | "draft";
    specReviewResponses?: string[];
    specTcReviewResponses?: string[];
    onApplyFixes?: (request: { prompt: string; allowedTools?: string[] }) => void;
    onPlanFixes?: (request: { prompt: string; allowedTools?: string[] }) => void;
  },
) {
  const requests: Array<{ step: string; allowedTools?: string[]; prompt: string }> = [];
  const generatedStatus = options?.generatedStatus ?? "draft";
  const specReviewResponses = [...(options?.specReviewResponses ?? [])];
  const specTcReviewResponses = [...(options?.specTcReviewResponses ?? [])];
  return {
    requests,
    getConfig() {
      return { templates: {} };
    },
    getRunner(step: string) {
      return {
        async run(request: { prompt: string; allowedTools?: string[] }) {
          requests.push({ step, allowedTools: request.allowedTools, prompt: request.prompt });
          if (step === FLOW_STEP.SPEC_REVIEW) {
            return {
              text: specReviewResponses.shift()
                ?? "{\"checklist\":[{\"item\":\"ok\",\"verdict\":\"pass\",\"evidence\":\"done\"}],\"issues\":[]}",
            };
          }
          if (step === FLOW_STEP.SPEC_TC_REVIEW) {
            return {
              text: specTcReviewResponses.shift()
                ?? "{\"checklist\":[{\"item\":\"ok\",\"verdict\":\"pass\",\"evidence\":\"done\"}],\"issues\":[]}",
            };
          }
          if (step === FLOW_STEP.APPLY_FIXES) {
            if (request.prompt.includes("以下のレビュー指摘に対して、一括修正のための計画を作成してください。")) {
              options?.onPlanFixes?.(request);
              return {
                text: JSON.stringify({
                  summary: "fix spec/tc ambiguity",
                  repairs: [{
                    goal: "align spec and test cases",
                    files: ["docs/spec/quiz/result.md", "tests/test-cases/quiz/result.md"],
                    instructions: ["clarify the ambiguous contract"],
                    constraints: [],
                    related_issues: [1],
                  }],
                  global_constraints: [],
                }),
              };
            }
            options?.onApplyFixes?.(request);
            return { text: "ok" };
          }
          const match = /## 出力先\n(.+?)\n/.exec(request.prompt);
          if (match) {
            const outputPath = match[1]!;
            mkdirSync(dirname(outputPath), { recursive: true });
            writeFileSync(
              outputPath,
              `---\nstatus: ${generatedStatus}\n---\n# generated by ${step}\n`,
              "utf-8",
            );
          }
          return { text: "ok" };
        },
      };
    },
  } as any;
}

async function captureConsole(run: () => Promise<void>): Promise<string[]> {
  const logs: string[] = [];
  const original = console.log;
  console.log = (...args: unknown[]) => { logs.push(args.join(" ")); };
  try {
    await run();
  } finally {
    console.log = original;
  }
  return logs;
}

test("DesignFlow generates draft spec and test cases, then runs spec_tc_review", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-"));
  const boundary = new Boundary(root);
  const registry = createRegistry(root);
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test", { baseDir: root });

  const logs = await captureConsole(() => flow.run("quiz/result", "結果ページを作る", logger));

  assert.match(readFileSync(join(root, "docs", "spec", "quiz", "result.md"), "utf-8"), /status: draft/);
  assert.match(readFileSync(join(root, "tests", "test-cases", "quiz", "result.md"), "utf-8"), /status: draft/);
  assert.deepEqual(
    registry.requests.map((request: { step: string }) => request.step),
    [FLOW_STEP.SPEC_GENERATE, FLOW_STEP.SPEC_REVIEW, FLOW_STEP.TEST_CASE_GENERATE, FLOW_STEP.SPEC_TC_REVIEW],
  );
  assert.equal(logs.some((line) => line.includes("spec_tc_review が完了しました")), true);
});

test("DesignFlow respects profile designLayout for output paths and allowed tools", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-layout-"));
  const boundary = new Boundary(root);
  const registry = createRegistry(root);
  const flow = new DesignFlow(boundary, registry as any, {
    designLayout: {
      specDir: "docs/spec/backend/{{category}}",
      testCaseDir: "backend/{{category}}/docs/test-cases",
    },
  } as any);
  const logger = new HarnessLogger("design-test-layout", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.match(readFileSync(join(root, "docs", "spec", "backend", "quiz", "result.md"), "utf-8"), /draft/);
  assert.match(readFileSync(join(root, "backend", "quiz", "docs", "test-cases", "result.md"), "utf-8"), /draft/);
  assert.deepEqual(registry.requests[0]?.allowedTools, [
    "Read",
    "Write(docs/spec/backend/quiz/*)",
    "Edit(docs/spec/backend/quiz/*)",
  ]);
  assert.deepEqual(registry.requests[2]?.allowedTools, [
    "Read",
    "Write(backend/quiz/docs/test-cases/*)",
    "Edit(backend/quiz/docs/test-cases/*)",
  ]);
});

test("DesignFlow no longer blocks test-case generation on draft spec", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-existing-"));
  mkdirSync(join(root, "docs", "spec", "quiz"), { recursive: true });
  writeFileSync(join(root, "docs", "spec", "quiz", "result.md"), "---\nstatus: draft\n---\n", "utf-8");
  const boundary = new Boundary(root);
  const registry = createRegistry(root);
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test-existing", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.equal(isReadyLikeStatus("approved"), true);
  assert.equal(isReadyLikeStatus("draft"), false);
  assert.match(readFileSync(join(root, "tests", "test-cases", "quiz", "result.md"), "utf-8"), /status: draft/);
  assert.deepEqual(
    registry.requests.map((request: { step: string }) => request.step),
    [FLOW_STEP.SPEC_REVIEW, FLOW_STEP.TEST_CASE_GENERATE, FLOW_STEP.SPEC_TC_REVIEW],
  );
});

test("DesignFlow falls back to bundled templates when project templates are absent", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-builtin-template-"));
  const boundary = new Boundary(root);
  const registry = createRegistry(root);
  const flow = new DesignFlow(boundary, registry as any);
  const logger = new HarnessLogger("design-test-builtin-template", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.match(registry.requests[0]?.prompt ?? "", /ルール間の相互作用/);
  assert.match(registry.requests[0]?.prompt ?? "", /# 具体例/);
  assert.match(registry.requests[0]?.prompt ?? "", /# 受け入れ基準/);
  assert.match(registry.requests[0]?.prompt ?? "", /各主要ルールに対して最低1つ/);
  assert.match(registry.requests[1]?.prompt ?? "", /仕様書整合性レビュー/);
  assert.match(registry.requests[1]?.prompt ?? "", /公開 API の形状明示/);
  assert.match(registry.requests[1]?.prompt ?? "", /テストダブルのシグネチャ決定可能性/);
  assert.match(registry.requests[1]?.prompt ?? "", /## requirements/);
  assert.match(registry.requests[2]?.prompt ?? "", /# 検証焦点/);
  assert.match(registry.requests[2]?.prompt ?? "", /# 網羅性チェック/);
  assert.match(registry.requests[2]?.prompt ?? "", /\[要仕様追記\]/);
  assert.match(registry.requests[2]?.prompt ?? "", /受け入れ基準の各項目に対応するテストケース/);
  assert.match(registry.requests[2]?.prompt ?? "", /テストの種類ごとに検証焦点を明示/);
  assert.match(registry.requests[2]?.prompt ?? "", /対応関係を網羅性チェックセクションに記載/);
  assert.match(registry.requests[3]?.prompt ?? "", /DTO \/ 入出力フィールドの振る舞い/);
  assert.match(registry.requests[3]?.prompt ?? "", /TC の「前提」欄の境界/);
  assert.match(registry.requests[3]?.prompt ?? "", /TC の「期待結果」の検証スコープ/);
  assert.match(registry.requests[3]?.prompt ?? "", /## requirements/);
});

test("DesignFlow loads project template overrides from .harness/resources/templates", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-project-template-"));
  mkdirSync(join(root, ".harness", "resources", "templates"), { recursive: true });
  writeFileSync(join(root, ".harness", "resources", "templates", "spec-template.md"), "# project spec template\n", "utf-8");
  writeFileSync(join(root, ".harness", "resources", "templates", "test-case-template.md"), "# project test-case template\n", "utf-8");
  const boundary = new Boundary(root);
  const registry = createRegistry(root);
  const flow = new DesignFlow(boundary, registry as any);
  const logger = new HarnessLogger("design-test-project-template", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.match(registry.requests[0]?.prompt ?? "", /project spec template/);
  assert.match(registry.requests[2]?.prompt ?? "", /project test-case template/);
});

test("DesignFlow passes combined spec and test-case scopes into apply_fixes during spec_tc_review", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-fixes-"));
  const boundary = new Boundary(root);
  let applyFixesRequest: { prompt: string; allowedTools?: string[] } | null = null;
  const registry = createRegistry(root, {
    specTcReviewResponses: [
      "{\"checklist\":[{\"item\":\"scope\",\"verdict\":\"fail\",\"evidence\":\"missing\"}],\"issues\":[{\"file\":\"docs/spec/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"spec と TC が曖昧\"}]}",
      "{\"checklist\":[{\"item\":\"scope\",\"verdict\":\"pass\",\"evidence\":\"done\"}],\"issues\":[]}",
    ],
    onApplyFixes(request) {
      applyFixesRequest = request;
    },
  });
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test-fixes", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.ok(applyFixesRequest);
  assert.deepEqual((applyFixesRequest as { allowedTools?: string[] }).allowedTools, [
    "Read",
    "Write(docs/spec/quiz/*)",
    "Edit(docs/spec/quiz/*)",
    "Write(tests/test-cases/quiz/*)",
    "Edit(tests/test-cases/quiz/*)",
  ]);
});

test("DesignFlow passes spec-only scope into apply_fixes during spec_review", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-spec-review-fixes-"));
  const boundary = new Boundary(root);
  let applyFixesRequest: { prompt: string; allowedTools?: string[] } | null = null;
  const registry = createRegistry(root, {
    specReviewResponses: [
      "{\"checklist\":[{\"item\":\"api\",\"verdict\":\"fail\",\"evidence\":\"missing\"}],\"issues\":[{\"file\":\"docs/spec/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"公開 API の形が未定義\"}]}",
      "{\"checklist\":[{\"item\":\"api\",\"verdict\":\"pass\",\"evidence\":\"done\"}],\"issues\":[]}",
    ],
    onApplyFixes(request) {
      applyFixesRequest = request;
    },
  });
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test-spec-review-fixes", { baseDir: root });

  await flow.run("quiz/result", "結果ページを作る", logger);

  assert.ok(applyFixesRequest);
  assert.deepEqual((applyFixesRequest as { allowedTools?: string[] }).allowedTools, [
    "Read",
    "Write(docs/spec/quiz/*)",
    "Edit(docs/spec/quiz/*)",
  ]);
});

test("DesignFlow passes requirements into spec reviews and apply_fixes planning", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-requirements-"));
  const boundary = new Boundary(root);
  const requirements = "タグフィルタは cross-store join が必要なためスコープ外。topic 解決機能は不要。";
  let planPrompt = "";
  const registry = createRegistry(root, {
    specReviewResponses: [
      "{\"checklist\":[{\"item\":\"scope\",\"verdict\":\"fail\",\"evidence\":\"missing scope\"}],\"issues\":[{\"file\":\"docs/spec/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"topic の責務境界が未定義\"}]}",
      "{\"checklist\":[{\"item\":\"scope\",\"verdict\":\"pass\",\"evidence\":\"done\"}],\"issues\":[]}",
    ],
    onPlanFixes(request) {
      planPrompt = request.prompt;
    },
  });
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test-requirements", { baseDir: root });

  await flow.run("quiz/result", requirements, logger);

  assert.match(registry.requests[1]?.prompt ?? "", /cross-store join が必要なためスコープ外/);
  assert.match(registry.requests[3]?.prompt ?? "", /cross-store join が必要なためスコープ外/);
  assert.match(planPrompt, /## スコープ制約（requirements 原文）/);
  assert.match(planPrompt, /スコープ外/);
  assert.match(planPrompt, /除外する修正も有効/);
});

test("DesignFlow spec_review stops after two non-converging cycles", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-spec-review-drift-"));
  const boundary = new Boundary(root);
  const registry = createRegistry(root, {
    specReviewResponses: [
      "{\"checklist\":[{\"item\":\"api\",\"verdict\":\"fail\",\"evidence\":\"missing\"}],\"issues\":[{\"file\":\"docs/spec/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"ambiguous api 1\"}]}",
      "{\"checklist\":[{\"item\":\"api\",\"verdict\":\"fail\",\"evidence\":\"still missing\"}],\"issues\":[{\"file\":\"docs/spec/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"ambiguous api 2\"}]}",
    ],
  });
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test-spec-review-drift", { baseDir: root });

  await assert.rejects(
    () => flow.run("quiz/result", "結果ページを作る", logger),
    DriftError,
  );
});

test("DesignFlow spec_tc_review stops after two non-converging cycles", async () => {
  const root = mkdtempSync(join(tmpdir(), "harness-design-flow-drift-"));
  const boundary = new Boundary(root);
  const registry = createRegistry(root, {
    specTcReviewResponses: [
      "{\"checklist\":[{\"item\":\"scope\",\"verdict\":\"fail\",\"evidence\":\"missing\"}],\"issues\":[{\"file\":\"docs/spec/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"ambiguous 1\"}]}",
      "{\"checklist\":[{\"item\":\"scope\",\"verdict\":\"fail\",\"evidence\":\"still missing\"}],\"issues\":[{\"file\":\"tests/test-cases/quiz/result.md\",\"line\":1,\"severity\":\"major\",\"description\":\"ambiguous 2\"}]}",
    ],
  });
  const flow = new DesignFlow(boundary, registry);
  const logger = new HarnessLogger("design-test-drift", { baseDir: root });

  await assert.rejects(
    () => flow.run("quiz/result", "結果ページを作る", logger),
    DriftError,
  );
});
